---
title: "Codebook Unit 5 Assignment"
author: "Blaine Brewer"
date: "February 12, 2019"
output: 
  html_document:
    keep_md: yes
    
---

### Codebook

#### Project Description
The purpose of this excercise it the munging and merging of data associated with popular boys and girls names in the United States in the years 2015 and 2016.

#### Collection of the raw data
The data (yob2015.txt and yob2016.txt) was collected from a GitHub repo at https://github.com/BivinSadler/MSDS-6306-Doing-Data-Science/tree/master/Unit%205

#### Description on how to create the tidy data file
1. Download the data from the aforementioned repo.
2. Import the yob2016.txt file into RStudio.
3. Add column names to the data - name, sex, and count respectively.
4. Remove the name "Fionayyy" from the dataset.
3. Import the yob2015.txt file inot RStudio.
4. Add column names to the data - name, sex, and count respectively.
5. Merge the two data frames together by name.

#### Cleaning the data
There is a record "Fionayyy" that was duplicated and mispelled.  This record should be removed as highlighted above.

#### Description of the variables
##### yob2015.txt
Columns: 3
Rows: 33,063

name - character - the name in the 2015 popular U.S. names data table
sex - character - the sex of the person with the associated name
count - numeric - the number of people named that name in 2015

##### yob2016.txt
Columns: 3
Rows: 32,869

name - character - the name in the 2016 popular U.S. names data table
sex (M or F) - character - the sex of the person with the associated name
count - numeric - the number of people named that name in 2016

####Sources
https://github.com/BivinSadler/MSDS-6306-Doing-Data-Science/tree/master/Unit%205